# Generated by Django 5.1 on 2024-08-11 07:31

import shortener_app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AliasUrl',
            fields=[
                ('alias', models.CharField(default=shortener_app.utils.get_random_alias, max_length=8, primary_key=True, serialize=False)),
                ('url', models.URLField()),
            ],
        ),
    ]
