# Generated by Django 5.1 on 2024-08-11 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AliasUrl',
            new_name='AliasedUrl',
        ),
    ]
